language: java
jdk: oraclejdk8
install: true
script: ./mvnw clean package

notifications:
  email: false

deploy:
  provider: releases
  file: README.md
  on:
    repo: LeMikaelF/recitalinteractif
    tags: true
