language: java
jdk:
  - openjdk8
install: true
script: mvn clean package -e

notifications:
  email: false

deploy:
  provider: releases
  file: README.md
  on:
    repo: LeMikaelF/recitalinteractif
    tags: true
