
language: java
jdk:
  - openjdk8

before_install:
  - sudo apt-get install -y openjfx

script: mvn clean package -e

notifications:
  email: false

deploy:
  provider: releases
  file: README.md
  on:
    repo: LeMikaelF/recitalinteractif
tags: true
