language: java

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

notifications:
  email: false



deploy:
  provider: releases
  file: README.md
  on:
    repo: LeMikaelF/recitalinteractif
    tags: true
